name: Sync Upstream
on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:
permissions:
  contents: write
  actions: read
env:
  UPSTREAM_OWNER: "AstideLabs"
  UPSTREAM_REPO: "android_kernel_xiaomi_sm8250"
jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["android16-aptusitu", "android16-aptusitu-new"]
    steps:
      - id: check-branch
        run: |
          if git ls-remote --exit-code --heads https://github.com/${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}.git ${{ matrix.branch }} > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
      - if: steps.check-branch.outputs.exists == 'true'
        uses: actions/checkout@v6
        with:
          repository: ${{ env.UPSTREAM_OWNER }}/${{ env.UPSTREAM_REPO }}
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          token: ${{ secrets.fok777 }}
      - if: steps.check-branch.outputs.exists == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - if: steps.check-branch.outputs.exists == 'true'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.fok777 }}@github.com/fok777/f.git
          git push --force origin ${{ matrix.branch }}
          git push origin --tags
